name: padavan build
on:
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      build_variant: ${{ matrix.build_variant }}
      targets: ${{ matrix.targets }}
      images_dir: /opt/images
    strategy:
      matrix:
        include:
          - build_variant: "mt7620"
            targets: "PSG1218"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install libtool-bin gperf python3-docutils autopoint gettext

      - name: Run shellcheck
        run: sh ./trunk/tools/shellcheck.sh

      - name: Prepare toolchain
        run: |
          cd toolchain-mipsel
          sh dl_toolchain.sh

      - name: Start build
        run: |
          cd trunk
          mkdir -p ${images_dir}
          for m in $targets; do fakeroot ./build_firmware_ci $m; \
          if [ $? = 0 ]; then cp -f images/*.trx ${images_dir}/$m.trx; else exit 1; fi; \
          ./clear_tree_simple >/dev/null 2>&1; done

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Padavan-${{ env.targets }}
          path: ${{ env.images_dir }}
