name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - build_variant: "mt7620"
            targets: "PSG1218"
          - build_variant: "mt7621"
            targets: "RM2100"
    env:
      build_variant: ${{ matrix.build_variant }}
      targets: ${{ matrix.targets }}
      images_dir: /opt/images

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free Disk Space
        uses: FirelightFlagboy/gh-runner-free-disk-space@main

      - name: Initialization environment
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq upgrade
          sudo -E apt-get -yqq install autopoint gettext gperf libtool-bin python3-docutils
          sudo -E apt-get -yqq autoremove
          sudo -E apt-get -yqq autoclean
          sudo -E apt-get -yqq clean
          sudo -E systemctl daemon-reload

      - name: Prepare
        run: |
          sh ./trunk/tools/shellcheck.sh
          cd toolchain-mipsel
          sh dl_toolchain.sh

      - name: Build Padavan
        run: |
          cd trunk
          mkdir -p ${images_dir}
          for m in $targets; do fakeroot ./build_firmware_ci $m; \
          if [ $? = 0 ]; then cp -f images/*.trx ${images_dir}/$m.trx; else exit 1; fi; \
          ./clear_tree_simple >/dev/null 2>&1; done

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Padavan-${{ env.targets }}
          path: ${{ env.images_dir }}

      - name: Delete old Releases and Workflows
        if: matrix.targets == 'PSG1218'
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          releases_keep_latest: 0
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: 1
          gh_token: ${{secrets.GITHUB_TOKEN}}
