name: Update

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Update
        run: |
          sudo apt-get update
          rm -rf .travis.yml
          rm -rf changes.eng.txt
          rm -rf Dockerfile
          rm -rf readme.eng.txt
          rm -rf readme.rus.txt

      - name: Commit Files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
